/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasegui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.sql.ResultSetMetaData;
import javax.swing.*;
import javax.swing.table.TableColumn;
/**
 *
 * @author Aust1_000
 */
public class Reports extends javax.swing.JFrame {
private MyDBConnection mdbc;
private java.sql.Statement stmt;
Connection conn;
Vector columnNames; 
Vector data; 
JTable table, table2, table3;
    /**
     * Creates new form Reports
     */
    public Reports() throws Exception {
        mdbc=new MyDBConnection();
         mdbc.init();
         conn=mdbc.getMyConnection();
         stmt= conn.createStatement();
        
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane(table);
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane(table2);
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane(table3);
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Submit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1))
        );

        jScrollPane2.setViewportView(jPanel2);

        jTabbedPane1.addTab("Sold/Sale", jScrollPane2);

        jToggleButton2.setText("Submit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2))
        );

        jTabbedPane1.addTab("Leased", jPanel3);

        jToggleButton3.setText("Submit");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3))
        );

        jTabbedPane1.addTab("Agents", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String quotate(String content){
    
        return "'"+content+"'";
    }
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
             
             String selectString;
             String address = ""; //Declare a new variable to store name
                String price = "0"; //Declare a new variable for price.
Connection myConnection;
      columnNames = new Vector(); 
      data = new Vector();
try{
selectString = "select address, price, agentName, phoneNumber from property join agent on property.agent = agent.agentID where status IN (2,3,5,6)";

PreparedStatement statement = conn.prepareStatement(selectString);      //use question marks to simplify statement.

ResultSet rs = statement.executeQuery();     // execute the query
ResultSetMetaData metaData = rs.getMetaData();
int columns = metaData.getColumnCount();
for (int i = 1; i <= columns; i++) {
     columnNames.addElement(metaData.getColumnName(i));
}
while ( rs.next() )
{

          Vector row = new Vector(columns);
          for (int i = 1; i <= columns; i++) {
                  row.addElement(rs.getObject(i));
           }
            data.addElement(row);
     
     // temporarily store the current value in the name column
     //address = rs.getString("name");
     //propertyAddress.setText(address);
     // temporarily store the current value in the price column
     //price = rs.getString("price");
    // propertyPrice.setText(price);
     //print each record in the result set.
     
}
table = new JTable(data, columnNames);
TableColumn column;
for (int i = 0; i < table.getColumnCount(); i++) {
     column = table.getColumnModel().getColumn(i);
     column.setMaxWidth(250);
}
rs.close();           //close the result set
statement.close(); //close the prepared statement
} catch (SQLException e) {}        
    
            getContentPane().removeAll();
            initComponents();   
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
                    
             String selectString;
             String address = ""; //Declare a new variable to store name
                String price = "0"; //Declare a new variable for price.
Connection myConnection;
     columnNames = new Vector(); 
     data = new Vector();

try{
selectString = "select address, price, agentName, phoneNumber from property join agent on property.agent = agent.agentID where status IN (1,7,8)";

PreparedStatement statement = conn.prepareStatement(selectString);      //use question marks to simplify statement.

ResultSet rs = statement.executeQuery();     // execute the query
ResultSetMetaData metaData = rs.getMetaData();
int columns = metaData.getColumnCount();
for (int i = 1; i <= columns; i++) {
     columnNames.addElement(metaData.getColumnName(i));
}
while ( rs.next() )
{

          Vector row = new Vector(columns);
          for (int i = 1; i <= columns; i++) {
                  row.addElement(rs.getObject(i));
           }
            data.addElement(row);
     
     // temporarily store the current value in the name column
     //address = rs.getString("name");
     //propertyAddress.setText(address);
     // temporarily store the current value in the price column
     //price = rs.getString("price");
    // propertyPrice.setText(price);
     //print each record in the result set.
     
}
table2 = new JTable(data, columnNames);
TableColumn column;
for (int i = 0; i < table2.getColumnCount(); i++) {
     column = table2.getColumnModel().getColumn(i);
     column.setMaxWidth(250);
}
rs.close();           //close the result set
statement.close(); //close the prepared statement
} catch (SQLException e) {}        
    
            getContentPane().removeAll();
            initComponents(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
                   String selectString;
             String address = ""; //Declare a new variable to store name
                String price = "0"; //Declare a new variable for price.
Connection myConnection;
     columnNames = new Vector(); 
     data = new Vector();

try{
selectString = "select agentName, assistantName, office, assistantPhone, assistantOffice from agent join assistant on agent.assistants = assistant.assistantID";

PreparedStatement statement = conn.prepareStatement(selectString);      //use question marks to simplify statement.

ResultSet rs = statement.executeQuery();     // execute the query
ResultSetMetaData metaData = rs.getMetaData();
int columns = metaData.getColumnCount();
for (int i = 1; i <= columns; i++) {
     columnNames.addElement(metaData.getColumnName(i));
}
while ( rs.next() )
{

          Vector row = new Vector(columns);
          for (int i = 1; i <= columns; i++) {
                  row.addElement(rs.getObject(i));
           }
            data.addElement(row);
     
     // temporarily store the current value in the name column
     //address = rs.getString("name");
     //propertyAddress.setText(address);
     // temporarily store the current value in the price column
     //price = rs.getString("price");
    // propertyPrice.setText(price);
     //print each record in the result set.
     
}
table3 = new JTable(data, columnNames);
TableColumn column;
for (int i = 0; i < table3.getColumnCount(); i++) {
     column = table3.getColumnModel().getColumn(i);
     column.setMaxWidth(250);
}
rs.close();           //close the result set
statement.close(); //close the prepared statement
} catch (SQLException e) {}        
    
            getContentPane().removeAll();
            initComponents();   // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                   try{
                 new Reports().setVisible(true);
                }
                catch(Exception e)
                {}
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
